/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;
/**
 *
 * @author anzal
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    Person person;
    
    public CreatePersonJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFname1 = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblWebsiteURL = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPincode = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtWebsiteURL = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPhne = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPincde = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        btnBrowseImage = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Person Information");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblFname1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblFname1.setText("First_Name : ");

        lblLname.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblLname.setText("Last_Name : ");

        lblSSN.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblSSN.setText("SSN : ");

        lblWebsiteURL.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblWebsiteURL.setText("Website_URL : ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblEmail.setText("Email : ");

        lblPicture.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPicture.setText("Picture : ");

        lblAge.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblAge.setText("Age : ");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPhone.setText("Phone : ");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblUsername.setText("Username : ");

        lblPincode.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPincode.setText("Pincode : ");

        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });

        txtPhne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhneActionPerformed(evt);
            }
        });

        lblImage.setText("Upload an image");
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBrowseImage.setText("Browse");
        btnBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseImageActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLname)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWebsiteURL)
                            .addComponent(lblEmail)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone)
                            .addComponent(lblSSN)
                            .addComponent(lblUsername)
                            .addComponent(lblPincode)
                            .addComponent(lblPicture))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnBrowseImage))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtPhne, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtWebsiteURL)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtUsername)
                                    .addComponent(txtPincde))))
                        .addGap(0, 251, Short.MAX_VALUE))))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblFname1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFname)
                            .addComponent(txtLname)
                            .addComponent(txtSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnSave)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname1)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWebsiteURL)
                    .addComponent(txtWebsiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPincode)
                    .addComponent(txtPincde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseImage)
                    .addComponent(lblPicture))
                .addGap(27, 27, 27)
                .addComponent(btnSave)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtPhneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhneActionPerformed

    private void btnBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseImageActionPerformed
        // TODO add your handling code here:
      
        
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            System.out.println(selectedImagePath);
            JOptionPane.showMessageDialog(null, selectedImagePath);
            
            person.setPicture(selectedImagePath);
            System.out.println("displaypath:" + person.getPicture());
            ImageIcon ii = new ImageIcon(selectedImagePath);
            Image image1 = ii.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(image1));
        }  
    }//GEN-LAST:event_btnBrowseImageActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String Fname = txtFname.getText();
        String Lname = txtLname.getText();
        String SSN = txtSSN.getText();
        String Website_URL = txtWebsiteURL.getText();
        String email = txtEmail.getText();
        String age = txtAge.getText();
        String phone = txtPhne.getText();
        String username = txtUsername.getText();
        String pincode = txtPincde.getText();
        
        
        if (containsOnlyLetters(Fname) && isEmptyValue(Fname)) {
                    person.setFirst_name(txtFname.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for First name: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isEmptyValue(Lname) && containsOnlyLetters(Lname)) {
                   person.setLast_name(txtLname.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input Last name: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isEmptyValue(SSN) && containsOnlyLetters(SSN)) {
                   person.setSsn(txtSSN.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input SSN: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isEmptyValue(Website_URL)) {
                   person.setWebsite_url(txtWebsiteURL.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input Website URL: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isValidEmail(email) && isEmptyValue(email)) {
                   person.setEmail(txtEmail.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Email: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isValidNumber(age) && isEmptyValue(age)) {
                   person.setAge(txtAge.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Age: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isValidPhoneNumber(phone) && isEmptyValue(phone)) {
                   person.setPhone(txtPhne.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Phone Number: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isEmptyValue(username)) {
                   person.setUsername(txtUsername.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Username: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isValidNumber(pincode) && isEmptyValue(pincode)) {
                   person.setPincode(txtPincde.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Pincode: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
          
       JOptionPane.showMessageDialog(this,"Person Information Saved "); 
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


     private static boolean isEmptyValue(String name) {
        return !name.isEmpty();
    }
    
     
     private static boolean isValidNumber(String number) {
        String regex = "^[0-9]*$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(number);

        return matcher.matches();
    }
     
     private boolean containsOnlyLetters(String name) {
                return name.matches("^[a-zA-Z]*$");
            }
     
     private static boolean isValidEmail(String email1) {
        String reg = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(reg);
        Matcher matcher = pattern.matcher(email1);

        return matcher.matches();
    }
     
     private static boolean isValidPhoneNumber(String phone) {
        String regex = "^[0-9\\-\\s]+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(phone);

        return matcher.matches();
    }
     
     
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblPincode;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWebsiteURL;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhne;
    private javax.swing.JTextField txtPincde;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtWebsiteURL;
    // End of variables declaration//GEN-END:variables
}
