/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.Address;
import model.Doctor;
import model.Driver;
import model.Insurance_coverage;
import model.Patient;
import model.Person;
import model.Vehicle_Registration;


/**
 *
 * @author anzal
 */
public class DisplayReportJPanel extends javax.swing.JPanel {

    Person person;
    Address address;
    Driver driver;
    Vehicle_Registration vehicle;
    Patient patient;
    Doctor doctor;
    Insurance_coverage insurance;
    
    public DisplayReportJPanel(Person person , Address address, Driver driver, Vehicle_Registration vehicle ,Patient patient, Doctor doctor,Insurance_coverage insurance) {
        initComponents();
        this.person = person;
        this.address = address;
        this.driver = driver;
        this.vehicle = vehicle;
        this.patient = patient;
        this.doctor  = doctor;
        this.insurance = insurance;
        
        displayPerson();
        displayAddress();
        displayDriver();
        displayVehicle();
        displayPatient();
        displayDoctor();
        displayInsuranceCoverage();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLicense = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        lblFname1 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtPhne = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblPincode = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPincde = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        lblWebsiteURL = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtWebsiteURL = new javax.swing.JTextField();
        lblimage = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbl_gps = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtGPS = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblLicense1 = new javax.swing.JLabel();
        txtLicense1 = new javax.swing.JTextField();
        lblCarModel = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lbl_CarBrand = new javax.swing.JLabel();
        txtCarModel = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtCarBrand = new javax.swing.JTextField();
        txtPatientID = new javax.swing.JTextField();
        txtPrimaryDoctor = new javax.swing.JTextField();
        txtLastVisit = new javax.swing.JTextField();
        txtNextAppointment = new javax.swing.JTextField();
        lblPatientID = new javax.swing.JLabel();
        lblPrimaryDoctor = new javax.swing.JLabel();
        lblLastVisit = new javax.swing.JLabel();
        lblNextAppointment = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        lblOnMedication = new javax.swing.JLabel();
        txtDrNum = new javax.swing.JTextField();
        lblVisitTime = new javax.swing.JLabel();
        lblDoctorNumber = new javax.swing.JLabel();
        txtDrName = new javax.swing.JTextField();
        txtOfficeAddr = new javax.swing.JTextField();
        txtDrID = new javax.swing.JTextField();
        txtSpecialty = new javax.swing.JTextField();
        lblDrNmae = new javax.swing.JLabel();
        txtVisitFee = new javax.swing.JTextField();
        lblDrAddress = new javax.swing.JLabel();
        txtVisitTime = new javax.swing.JTextField();
        lblDoctorID = new javax.swing.JLabel();
        lblSpecialty = new javax.swing.JLabel();
        lblVisitFee = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBenefits = new javax.swing.JTextArea();
        txtPremium = new javax.swing.JTextField();
        txtInsuranceAddr = new javax.swing.JTextField();
        txtCorporateID = new javax.swing.JTextField();
        lblCorporate = new javax.swing.JLabel();
        lblInsuranceAddr = new javax.swing.JLabel();
        lblPremium = new javax.swing.JLabel();
        lblDeductable = new javax.swing.JLabel();
        txtDeductable = new javax.swing.JTextField();
        lblBenefits = new javax.swing.JLabel();
        txtAllergies = new javax.swing.JTextField();
        txtOnMedication = new javax.swing.JTextField();
        lblInsuranceCoverage = new javax.swing.JLabel();
        txtInsuranceCoverage = new javax.swing.JTextField();
        lblPersonTitle = new javax.swing.JLabel();
        lblAddressTitle = new javax.swing.JLabel();
        lblLicenseTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        lblLicense.setText("License Number : ");

        setBackground(new java.awt.Color(204, 255, 255));

        lblFname1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblFname1.setText("First_Name : ");

        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });

        lblLname.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblLname.setText("Last_Name : ");

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblAge.setText("Age : ");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPhone.setText("Phone : ");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblUsername.setText("Username : ");

        txtPhne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhneActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(153, 255, 255));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Patient Report");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPincode.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPincode.setText("Pincode : ");

        txtPincde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPincdeActionPerformed(evt);
            }
        });

        lblSSN.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblSSN.setText("SSN : ");

        lblWebsiteURL.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblWebsiteURL.setText("Website_URL : ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblEmail.setText("Email : ");

        lblimage.setText("Image of Patient");
        lblimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPicture.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPicture.setText("Patient's Picture");

        lbl_gps.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_gps.setText("GPS_location");

        lblCountry.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCountry.setText("Country");

        lblcity.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblcity.setText("City");

        lblState.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblState.setText("State");

        lblLicense1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblLicense1.setText("License Number : ");

        lblCarModel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCarModel.setText("Car Model : ");

        lblSerialNumber.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblSerialNumber.setText("Serial Number : ");

        lbl_CarBrand.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_CarBrand.setText("Car Brand : ");

        txtCarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarModelActionPerformed(evt);
            }
        });

        txtCarBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarBrandActionPerformed(evt);
            }
        });

        txtLastVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastVisitActionPerformed(evt);
            }
        });

        txtNextAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNextAppointmentActionPerformed(evt);
            }
        });

        lblPatientID.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPatientID.setText("Patient ID : ");

        lblPrimaryDoctor.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPrimaryDoctor.setText("Primary Doctor : ");

        lblLastVisit.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblLastVisit.setText("Last Visit : ");

        lblNextAppointment.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNextAppointment.setText("Next Appointment : ");

        lblAllergies.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblAllergies.setText("Allergies  : ");

        lblOnMedication.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblOnMedication.setText("OnMedication : ");

        txtDrNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrNumActionPerformed(evt);
            }
        });

        lblVisitTime.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblVisitTime.setText("Visit Time : ");

        lblDoctorNumber.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblDoctorNumber.setText("Doctor Number : ");

        txtOfficeAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOfficeAddrActionPerformed(evt);
            }
        });

        lblDrNmae.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblDrNmae.setText("Doctor Name : ");

        txtVisitFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVisitFeeActionPerformed(evt);
            }
        });

        lblDrAddress.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblDrAddress.setText("Office Address  : ");

        lblDoctorID.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblDoctorID.setText("Doctor_ID : ");

        lblSpecialty.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblSpecialty.setText("Specialty : ");

        lblVisitFee.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblVisitFee.setText("Visit Fee : ");

        txtBenefits.setColumns(20);
        txtBenefits.setRows(5);
        jScrollPane1.setViewportView(txtBenefits);

        txtInsuranceAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuranceAddrActionPerformed(evt);
            }
        });

        lblCorporate.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCorporate.setText("Corporate ID : ");

        lblInsuranceAddr.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblInsuranceAddr.setText("Insurance Address : ");

        lblPremium.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPremium.setText("Premium");

        lblDeductable.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblDeductable.setText("Deductable : ");

        lblBenefits.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblBenefits.setText("Benefits: ");

        txtOnMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOnMedicationActionPerformed(evt);
            }
        });

        lblInsuranceCoverage.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblInsuranceCoverage.setText("Insurance Coverage : ");

        txtInsuranceCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuranceCoverageActionPerformed(evt);
            }
        });

        lblPersonTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblPersonTitle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblPersonTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonTitle.setText("Person Details :");
        lblPersonTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAddressTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblAddressTitle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAddressTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddressTitle.setText("Person's Address : ");
        lblAddressTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLicenseTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblLicenseTitle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblLicenseTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLicenseTitle.setText("Driver's License Number : ");
        lblLicenseTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vehicle Registration Information : ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Patient's Information : ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Doctor's Information : ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Insurance Coverage Details : ");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLicenseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddressTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCountry, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(64, 64, 64)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_gps)
                                            .addGap(36, 36, 36)
                                            .addComponent(txtGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(101, 101, 101)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_CarBrand)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                            .addComponent(txtCarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblCarModel)
                                                .addComponent(lblSerialNumber))
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCarModel, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                                .addComponent(txtSerialNumber))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLicense1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLicense1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(97, 97, 97)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLname)
                                    .addComponent(lblSSN)
                                    .addComponent(lblWebsiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUsername)
                                    .addComponent(lblPhone)
                                    .addComponent(lblPincode))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtWebsiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(182, 182, 182)
                                        .addComponent(lblPicture)
                                        .addGap(0, 64, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPhne, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtPincde, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPersonTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(32, 32, 32)))
                                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblInsuranceCoverage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDeductable)
                                    .addComponent(lblPremium)
                                    .addComponent(lblCorporate)
                                    .addComponent(lblDoctorNumber)
                                    .addComponent(lblVisitTime)
                                    .addComponent(lblVisitFee)
                                    .addComponent(lblSpecialty)
                                    .addComponent(lblDoctorID)
                                    .addComponent(lblDrAddress)
                                    .addComponent(lblDrNmae)
                                    .addComponent(lblInsuranceAddr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBenefits))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtPremium, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                                .addComponent(txtInsuranceAddr, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDeductable, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDrNum, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVisitTime, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVisitFee, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDrID, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOfficeAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDrName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtAllergies, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(txtOnMedication, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOnMedication)
                                    .addComponent(lblLastVisit)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPatientID)
                                        .addComponent(lblPrimaryDoctor, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblNextAppointment)
                                    .addComponent(lblAllergies))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(txtLastVisit, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(txtPatientID, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(txtNextAppointment))))
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPersonTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFname1)
                                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSSN)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtWebsiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblWebsiteURL)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lblPicture)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPincde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPincode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAddressTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_gps))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCountry))
                        .addGap(18, 18, 18)
                        .addComponent(lblLicenseTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLicense1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicense1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarModel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSerialNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CarBrand))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrimaryDoctor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastVisit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNextAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNextAppointment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAllergies)
                            .addComponent(txtAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOnMedication)
                            .addComponent(txtOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInsuranceCoverage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDrNmae)
                            .addComponent(txtDrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOfficeAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDrID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDoctorID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSpecialty))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVisitFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVisitFee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVisitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVisitTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDrNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDoctorNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCorporate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInsuranceAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInsuranceAddr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPremium))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeductable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDeductable, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblBenefits)))
                        .addGap(26, 26, 26))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhneActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed
      
    private void txtCarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarModelActionPerformed

    private void txtCarBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarBrandActionPerformed

    private void txtLastVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastVisitActionPerformed

    private void txtDrNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrNumActionPerformed

    private void txtOfficeAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOfficeAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOfficeAddrActionPerformed

    private void txtVisitFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVisitFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVisitFeeActionPerformed

    private void txtInsuranceAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuranceAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsuranceAddrActionPerformed

    private void txtPincdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPincdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPincdeActionPerformed

    private void txtOnMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOnMedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOnMedicationActionPerformed

    private void txtInsuranceCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuranceCoverageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsuranceCoverageActionPerformed

    private void txtNextAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNextAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextAppointmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddressTitle;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCorporate;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDeductable;
    private javax.swing.JLabel lblDoctorID;
    private javax.swing.JLabel lblDoctorNumber;
    private javax.swing.JLabel lblDrAddress;
    private javax.swing.JLabel lblDrNmae;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname1;
    private javax.swing.JLabel lblInsuranceAddr;
    private javax.swing.JLabel lblInsuranceCoverage;
    private javax.swing.JLabel lblLastVisit;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblLicense1;
    private javax.swing.JLabel lblLicenseTitle;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblNextAppointment;
    private javax.swing.JLabel lblOnMedication;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPersonTitle;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblPincode;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblSpecialty;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblVisitFee;
    private javax.swing.JLabel lblVisitTime;
    private javax.swing.JLabel lblWebsiteURL;
    private javax.swing.JLabel lbl_CarBrand;
    private javax.swing.JLabel lbl_gps;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergies;
    private javax.swing.JTextArea txtBenefits;
    private javax.swing.JTextField txtCarBrand;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCorporateID;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDeductable;
    private javax.swing.JTextField txtDrID;
    private javax.swing.JTextField txtDrName;
    private javax.swing.JTextField txtDrNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtGPS;
    private javax.swing.JTextField txtInsuranceAddr;
    private javax.swing.JTextField txtInsuranceCoverage;
    private javax.swing.JTextField txtLastVisit;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtLicense1;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNextAppointment;
    private javax.swing.JTextField txtOfficeAddr;
    private javax.swing.JTextField txtOnMedication;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPhne;
    private javax.swing.JTextField txtPincde;
    private javax.swing.JTextField txtPremium;
    private javax.swing.JTextField txtPrimaryDoctor;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtSpecialty;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtVisitFee;
    private javax.swing.JTextField txtVisitTime;
    private javax.swing.JTextField txtWebsiteURL;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
    
        System.out.println();
        System.out.println("Report of Patient");
        System.out.println();
        txtFname.setText(person.getFirst_name());
        System.out.println("Patient First Name : "+person.getFirst_name());
        
        txtLname.setText(person.getLast_name());
        System.out.println("Patient Last Name : "+person.getLast_name());
        
        txtSSN.setText(person.getSsn());
        System.out.println("Patient SSN number : "+person.getSsn());
        
        txtWebsiteURL.setText(person.getWebsite_url());
        System.out.println("Website URL : "+person.getWebsite_url());
        
        txtEmail.setText(person.getEmail());
        System.out.println("Patient Email Address : "+person.getEmail());
        
        txtAge.setText(person.getAge());
        System.out.println("Patient Age : "+person.getAge());
        
        txtPhne.setText(person.getPhone());
        System.out.println("Patient Phone number : "+person.getPhone());
        
        txtUsername.setText(person.getUsername());
        System.out.println("Patient Username : "+person.getUsername());
        
        txtPincde.setText(person.getPincode());
        System.out.println("Patient Pincode : "+person.getPincode());
        
        String imagePathValue = person.getPicture();
       
        ImageIcon ii = new ImageIcon(imagePathValue);
        Image image1 = ii.getImage();
        lblimage.setIcon(new ImageIcon(image1));
    
    }

    private void displayAddress() {
        
        System.out.println();
        System.out.println("Patient's Address Details");
        System.out.println();
        
        txtGPS.setText(address.getGps_location());
        System.out.println("Patient GPS Co-Ordinate : "+address.getGps_location());
        
        txtCity.setText(address.getCity());
        System.out.println("Patient City : "+address.getCity());
        
        txtState.setText(address.getState());
        System.out.println("Patient State : "+address.getState());
        
        txtCountry.setText(address.getCountry());
        System.out.println("Patient Country : "+address.getCountry());
    
    }

    private void displayDriver() {
        
        System.out.println();
        System.out.println("Driver's Information");
        System.out.println();
        
        txtLicense1.setText(driver.getLicense_number());
        System.out.println("License Number : "+driver.getLicense_number());
        
    }

    private void displayVehicle() {
        
    
        System.out.println();
        System.out.println("Vehicle's Information");
        System.out.println();
        
        txtCarBrand.setText(vehicle.getCar_brand());
        System.out.println("Car Brand : "+vehicle.getCar_brand());
        
        
        txtCarModel.setText(vehicle.getCar_model());
        System.out.println("Car Model : "+vehicle.getCar_model());
        
        txtSerialNumber.setText(vehicle.getSerial_number());
        System.out.println("Serial Number : "+vehicle.getSerial_number());
        
    }

    private void displayPatient() {
       
    
        System.out.println();
        System.out.println("Patient's Other Information");
        System.out.println();
        
        txtPatientID.setText(patient.getPatient_id());
        System.out.println("Patient ID : "+patient.getPatient_id());
        
        txtPrimaryDoctor.setText(patient.getPrimary_doctor());
        System.out.println("Primary Doctor : "+patient.getPrimary_doctor());
        
        txtLastVisit.setText(patient.getLast_visit());
        System.out.println("Last Visit : "+patient.getLast_visit());
        
        txtNextAppointment.setText(patient.getNext_appointment());
        System.out.println("Next Appointment : "+patient.getNext_appointment());
        
        txtAllergies.setText(patient.getAllergies());
        System.out.println("Allergies Present : "+patient.getAllergies());
        
        txtOnMedication.setText(patient.getOnMedication());   
        System.out.println("OnMedication : "+patient.getOnMedication());
        
        txtInsuranceCoverage.setText(patient.getInsuranceCoverage());
        System.out.println("Insurance Coverage : "+patient.getInsuranceCoverage());
        
    }

    private void displayDoctor() {
       
        System.out.println();
        System.out.println("Doctor's Information");
        System.out.println();
    
        txtDrName.setText(doctor.getDoc_name());
        System.out.println("Doctor Name : "+doctor.getDoc_name());
        
        txtOfficeAddr.setText(doctor.getOffice_addr());
        System.out.println("Doctor Office Address : "+doctor.getOffice_addr());
        
        txtDrID.setText(doctor.getDoc_id());
        System.out.println("Doctor ID : "+doctor.getDoc_id());
        
        txtSpecialty.setText(doctor.getSpecialty());
        System.out.println("Doctor's Speciality : "+doctor.getSpecialty());
        
        txtVisitFee.setText(doctor.getVisit_fee());
        System.out.println("Doctor Visit Fee : "+doctor.getVisit_fee());
        
        txtVisitTime.setText(doctor.getVisit_time());
        System.out.println("Doctor Visit Time : "+doctor.getVisit_time());
        
        txtDrNum.setText(doctor.getDoc_number());
        System.out.println("Doctor Number : "+doctor.getDoc_number());
        
    }

    private void displayInsuranceCoverage() {
        
    
        System.out.println();
        System.out.println("Insurance Coverage Information");
        System.out.println();
        
        txtCorporateID.setText(insurance.getCorporate_id());
        System.out.println("Corporate ID : "+insurance.getCorporate_id());
        
        txtInsuranceAddr.setText(insurance.getInsurance_addr());
        System.out.println("Insurance Address : "+insurance.getInsurance_addr());
        
        txtPremium.setText(insurance.getPremium());
        System.out.println("Insurance Premium amount : "+insurance.getPremium());
        
        txtDeductable.setText(insurance.getDeductable());
        System.out.println("Deductable Amount : "+insurance.getDeductable());
        
        txtBenefits.setText((insurance.getBenefits()));
        System.out.println("Patient Benefits : "+insurance.getBenefits());
        
    }
}
