/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Insurance_coverage;

/**
 *
 * @author anzal
 */
public class InsuraneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuraneJPanel
     */
    
    Insurance_coverage insurance;
    
    public InsuraneJPanel(Insurance_coverage insurance) {
        initComponents();
        this.insurance = insurance;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCorporate = new javax.swing.JLabel();
        lblInsuranceAddr = new javax.swing.JLabel();
        lblPremium = new javax.swing.JLabel();
        lblBenefits = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBenefits = new javax.swing.JTextArea();
        txtPremium = new javax.swing.JTextField();
        txtInsuranceAddr = new javax.swing.JTextField();
        txtCorporateID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblDeductable = new javax.swing.JLabel();
        txtDeductable = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Insurance Coverage");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCorporate.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCorporate.setText("Corporate ID : ");

        lblInsuranceAddr.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblInsuranceAddr.setText("Insurance Address : ");

        lblPremium.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPremium.setText("Premium : ");

        lblBenefits.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblBenefits.setText("Benefits  : ");

        txtBenefits.setColumns(20);
        txtBenefits.setRows(5);
        jScrollPane1.setViewportView(txtBenefits);

        txtInsuranceAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuranceAddrActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblDeductable.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblDeductable.setText("Deductable : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInsuranceAddr)
                                    .addComponent(lblCorporate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtInsuranceAddr, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(txtCorporateID)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPremium)
                                    .addComponent(lblDeductable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBenefits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnSave)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorporate)
                    .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsuranceAddr)
                    .addComponent(txtInsuranceAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPremium)
                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeductable)
                    .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblBenefits))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(btnSave)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtInsuranceAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuranceAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsuranceAddrActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String cor_id = txtCorporateID.getText();
        String ins_addr = txtInsuranceAddr.getText();
        String premium = txtPremium.getText();
        String deductable = txtDeductable.getText();
        
        if (isEmptyValue(cor_id)) {
                     insurance.setCorporate_id(txtCorporateID.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Insurance Corporate ID: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
        if (isEmptyValue(ins_addr)) {
                     insurance.setInsurance_addr(txtInsuranceAddr.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Insurance Office Address: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isEmptyValue(premium)) {
                     insurance.setPremium(txtPremium.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Insurance Premium Amount: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isEmptyValue(deductable)) {
                     insurance.setDeductable(txtDeductable.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Insurance Deductable Amount: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        insurance.setBenefits(txtBenefits.getText());
        
        
        JOptionPane.showMessageDialog(this,"Insurance Coverage Information Saved ");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private static boolean isEmptyValue(String name) {
        return !name.isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCorporate;
    private javax.swing.JLabel lblDeductable;
    private javax.swing.JLabel lblInsuranceAddr;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtBenefits;
    private javax.swing.JTextField txtCorporateID;
    private javax.swing.JTextField txtDeductable;
    private javax.swing.JTextField txtInsuranceAddr;
    private javax.swing.JTextField txtPremium;
    // End of variables declaration//GEN-END:variables
}
