/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Patient;

/**
 *
 * @author anzal
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    
    Patient patient;
    
    public PatientJPanel(Patient patient) {
        initComponents();
        
        this.patient = patient;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        lblPrimaryDoctor = new javax.swing.JLabel();
        lblLastVisit = new javax.swing.JLabel();
        lblNextAppointment = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        lblOnMedication = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtPrimaryDoctor = new javax.swing.JTextField();
        txtLastVisit = new javax.swing.JTextField();
        txtNextAppointment = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        radioAllergiesYes = new javax.swing.JRadioButton();
        radioAllergiesNo = new javax.swing.JRadioButton();
        radioMedicationYes = new javax.swing.JRadioButton();
        radioMedicationNo = new javax.swing.JRadioButton();
        lblInsuranceCoverage = new javax.swing.JLabel();
        radioInsuranceYes = new javax.swing.JRadioButton();
        radioInsuranceNo = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Patient Information");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPatientID.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPatientID.setText("Patient ID : ");

        lblPrimaryDoctor.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPrimaryDoctor.setText("Primary Doctor : ");

        lblLastVisit.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblLastVisit.setText("Last Visit : ");

        lblNextAppointment.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNextAppointment.setText("Next Appointment : ");

        lblAllergies.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblAllergies.setText("Allergies  : ");

        lblOnMedication.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblOnMedication.setText("OnMedication : ");

        txtLastVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastVisitActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        radioAllergiesYes.setText("Yes");

        radioAllergiesNo.setText("No");

        radioMedicationYes.setText("Yes");

        radioMedicationNo.setText("No");
        radioMedicationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMedicationNoActionPerformed(evt);
            }
        });

        lblInsuranceCoverage.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblInsuranceCoverage.setText("Insurance Coverage : ");

        radioInsuranceYes.setText("Yes");
        radioInsuranceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioInsuranceYesActionPerformed(evt);
            }
        });

        radioInsuranceNo.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrimaryDoctor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPatientID)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInsuranceCoverage)
                            .addComponent(lblNextAppointment)
                            .addComponent(lblAllergies)
                            .addComponent(lblOnMedication)
                            .addComponent(lblLastVisit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrimaryDoctor)
                            .addComponent(txtNextAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radioAllergiesYes)
                                    .addComponent(radioMedicationYes)
                                    .addComponent(radioInsuranceYes)
                                    .addComponent(btnSave))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioMedicationNo)
                                    .addComponent(radioAllergiesNo)
                                    .addComponent(radioInsuranceNo)))
                            .addComponent(txtLastVisit)
                            .addComponent(txtPatientID))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrimaryDoctor)
                    .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNextAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNextAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergies)
                    .addComponent(radioAllergiesYes)
                    .addComponent(radioAllergiesNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMedicationNo)
                    .addComponent(radioMedicationYes)
                    .addComponent(lblOnMedication))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioInsuranceNo)
                    .addComponent(radioInsuranceYes)
                    .addComponent(lblInsuranceCoverage))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastVisitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String patient_id = txtPatientID.getText();
        String primary_doc = txtPrimaryDoctor.getText();
        
        if (isEmptyValue(patient_id)) {
                     patient.setPatient_id(txtPatientID.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Patient ID: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        if (isEmptyValue(primary_doc) && containsOnlyLetters(primary_doc)) {
                     patient.setPrimary_doctor(txtPrimaryDoctor.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Primary Doctor : ", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
        
        patient.setLast_visit(txtLastVisit.getText());
        patient.setNext_appointment(txtNextAppointment.getText());
        
        
        
        if(radioAllergiesYes.isSelected()){
            patient.setAllergies("Yes");    
        }
        else if(radioAllergiesNo.isSelected()) {
            patient.setAllergies("No");
        }
        else{
            //
        }
        
         if(radioMedicationYes.isSelected()){
            patient.setOnMedication("Yes");    
        }
        else if(radioMedicationNo.isSelected()) {
            patient.setOnMedication("No");
        }
        else{
            //
        }
        
         if(radioInsuranceYes.isSelected()){
            patient.setInsuranceCoverage("Yes");    
        }
        else if(radioInsuranceNo.isSelected()) {
            patient.setInsuranceCoverage("No");
        }
        else{
            //
        }
         
        JOptionPane.showMessageDialog(this,"Patient Information Saved ");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void radioMedicationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMedicationNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMedicationNoActionPerformed

    private void radioInsuranceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioInsuranceYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioInsuranceYesActionPerformed


     private static boolean isEmptyValue(String name) {
        return !name.isEmpty();
    }
    
     
     private boolean containsOnlyLetters(String name) {
                return name.matches("^[a-zA-Z]*$");
            }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblInsuranceCoverage;
    private javax.swing.JLabel lblLastVisit;
    private javax.swing.JLabel lblNextAppointment;
    private javax.swing.JLabel lblOnMedication;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radioAllergiesNo;
    private javax.swing.JRadioButton radioAllergiesYes;
    private javax.swing.JRadioButton radioInsuranceNo;
    private javax.swing.JRadioButton radioInsuranceYes;
    private javax.swing.JRadioButton radioMedicationNo;
    private javax.swing.JRadioButton radioMedicationYes;
    private javax.swing.JTextField txtLastVisit;
    private javax.swing.JTextField txtNextAppointment;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPrimaryDoctor;
    // End of variables declaration//GEN-END:variables
}
